# -*- coding: utf-8 -*-
"""CBOW.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RiblBbGMatBOLSZ3NfCHvhy6PWTcovhT
"""

import gensim.downloader as api

dataset = api.load("text8")
type(dataset)

doc_lengths = []
for x in dataset:
  l = len(x)
  doc_lengths.append(l)

import matplotlib.pyplot as plt
plt.hist(doc_lengths, bins=50)
plt.show()

import numpy as np
np.mean(doc_lengths), np.std(doc_lengths)

from tensorflow.keras.preprocessing.text import Tokenizer

vocab_size = 20_000
tokenizer = Tokenizer(num_words=vocab_size)
tokenizer.fit_on_texts(dataset)
sequences = tokenizer.texts_to_sequences(dataset)

tokenizer.num_words

len(tokenizer.word_index)

tokenizer.word_index

import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt

from tensorflow.keras.layers import Dense, Input, Embedding, Lambda
from tensorflow.keras.models import Model

import random
random.seed(1)
np.random.seed(1)
tf.random.set_seed(1)

context_size = 10
embedding_dim = 50

i = Input(shape=(context_size,))
x = Embedding(vocab_size, embedding_dim)(i)
x = Lambda(lambda t: tf.reduce_mean(t, axis=1))(x)
x = Dense(vocab_size, use_bias=False)(x)

model = Model(i,x)

model.summary()

half_context_size = context_size // 2

def data_generator(sequences,batch_size=128):
  X_batch = np.zeros((batch_size, context_size))
  Y_batch = np.zeros(batch_size)
  n_batches = int(np.ceil(len(sequences) / batch_size))
  while True:
    random.shuffle(sequences)
    #one epoch - one pass throught data
    for i in range(n_batches):
      batch_sequences = sequences[i * batch_size: (i+1) * batch_size]

      current_batch_size = len(batch_sequences)
      for ii in range(current_batch_size):
        seq = batch_sequences[ii]
        j = np.random.randint(0, len(seq) - context_size - 1)
        x1 = seq[j:j+half_context_size]
        x2 = seq[j+half_context_size+1:j+context_size+1]

        # Assign context words to X_batch
        X_batch[ii, :half_context_size] = x1
        X_batch[ii, half_context_size:] = x2

        # Assign target word to Y_batch
        y = seq[j+half_context_size]
        Y_batch[ii] = y

      yield X_batch[:current_batch_size], Y_batch[:current_batch_size]

model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer='adam',
    metrics=['accuracy']
)

batch_size = 128

r = model.fit(
    data_generator(sequences, batch_size),
    epochs = 10_000,
    steps_per_epoch=int(np.ceil(len(sequences) / batch_size))
)

#plot loss per iteration
plt.plot(r.history['loss'], label = 'loss')
plt.legend()

#plot accuracy per iteration
plt.plot(r.history['accuracy'], label = 'acc')

embeddings = model.layers[1].get_weights()[0]
embeddings

from sklearn.neighbors import NearestNeighbors
neighbors = NearestNeighbors(n_neighbors = 5, algorithm = 'ball_tree')
neighbors.fit(embeddings)

queen_idx = tokenizer.word_index['queen']
queen = embeddings[queen_idx:queen+idx+1]
distances,indices = neighbors/kneighbors(queen)

for idx in indices[0]:
  word = tokenizer.index_word[idx]
  print(word)

#king - man = queen - woman
def get_embedding(word):
  idx = tokenizer.word_index[word]
  return embeddings[idx:idx+1]

king = get_embedding('king')
man = get_embedding('man')
woman = get_embedding('woman')
query = king - man + woman

distances, indices = neighbors.kneighbors(query)
for idx in indices[0]:
  word = tokenizer.index_word[idx]
  print(word)